#!/bin/bash

count_added = 0
# From a list of usernames in un-3.txt and un-4.txt, create the users
for USERNAME in $(cat ./src/un-3.txt) $(cat ./src/un-4.txt)
do
    # create the user
    # useradd -m ${USERNAME}

    # check to see if the useradd command succeeded
    if [[ "${?}" -ne 0 ]]
    then
        echo "The account ${USERNAME} was NOT created." >&2
        exit 1
    fi

    # tell the user the account was created
    echo "The account ${USERNAME} was created."

    # increment the number of accounts created
    count_added=$((count_added + 1))

done

# sleep for 2.5 seconds
sleep 2.5

clear

# tell the user how many accounts were created
echo "Total number of accounts created: ${count_added}"
