#!/bin/bash

count_removed = 0
# From a list of usernames in un-3.txt and un-4.txt, delete the users
for USERNAME in $(cat ./src/un-3.txt) $(cat ./src/un-4.txt)
do
    # delete the user
    # userdel -r ${USERNAME}

    # check to see if the useradd command succeeded
    # we don't want to tell the user that an account was created when it hasn't been
    if [[ "${?}" -ne 0 ]]
    then
        echo "The account ${USERNAME} was NOT deleted." >&2
        exit 1
    fi

    # tell the user the account was created
    echo "The account ${USERNAME} was deleted."

    # increment the number of accounts created
    count_removed=$((count_removed + 1))

done

# sleep for 2.5 seconds
sleep 2.5

clear

# tell the user how many accounts were created
echo "Total number of accounts created: ${count_removed}"
